### PR TITLE
Add 16×16 micro icons

### PR DESCRIPTION
**Pull request by brennanangel**
@nandorojo I realized I still needed to adjust the code to add the new "micro" icons (16px). Sorry for the mistakes and fast follow!

I had to work around `src` being in `.gitignore` to update the icons but I think this looks right.

### CODE REVIEW

**Comment by nandorojo** [comment]
I'm a bit confused. Can you clarify your changes? src should be untouched and created from the generate script.

**Comment by nandorojo** [comment]
Are the mini ones 14px or 16px?

**Comment by brennanangel** [comment]
> I'm a bit confused. Can you clarify your changes? src should be untouched and created from the generate script.

That's what I thought too. Noticed that my last PR somehow updated the `src` folder when running `yarn prepare` despite being in `.gitignore` 

Anyways, please check out the recent changes in this PR that add the 16×16 **micro** icons (there aren't any 14px icons in Heroicons) :)

**Comment by brennanangel** [comment]
> Are the mini ones 14px or 16px?

That was a typo on my part. This adds the 16px "micro" ones that were just added in Heroicons v2.1.0: https://github.com/tailwindlabs/heroicons/releases/tag/v2.1.0

**Comment by nandorojo** [comment]
Got it, and is the source code there from the previous PR? for the icons themselves

**Comment by brennanangel** [comment]
> Got it, and is the source code there from the previous PR? for the icons themselves

Yes, the icons were [added in the previous PR](https://github.com/nandorojo/react-native-heroicons/pull/5/files)
image

Unfortunately, this will likely require a new release so users can have access to the "micro" icons

**Pull request merged**
